### ISSUE TITLE
is not a hex color!

### ISSUE THREAD

**Issue by davidbdyer** [Eworm/nova-hextosass#1]
I tried it on a few hex colors and it doesn't work. This #f4f4f4f4 becomes "[164, 173] is not a hex color!"

**Comment by Eworm** [comment]
Well, that's because [hex color codes start with a pound sign or hashtag (#) and are followed by six letters and/or numbers](https://www.pluralsight.com/blog/tutorials/understanding-hexadecimal-colors-simple). #f4f4f4f4 Is 8 letters/numbers wich isn't a hex code, so it works exactly as planned.

**Comment by davidbdyer** [comment]
Hex colors in CSS are more than just 3 and 6 characters. I don't know when they changed the spec, and I usually use HSL myself, but 8 and 4 character codes provide an alpha value.

**Comment by Eworm** [comment]
I did not know that! I've been thinking about the alpha value and how this would work here. Maybe I'll give adding it a try.
